### ISSUE TITLE
Autocomplete Ctrl+space

### ISSUE THREAD

**Issue by vharny** [jsonnext/codemirror-json-schema#121]
At the moment, I have the impression that you always need at least 1 character to display autocompletion.

It would be cool to have the list of possible object properties without having to type a first letter to get the list.

Just by pressing Ctrl+Space I'd like to have the complete list of possibilities.

Like here in the [Codemirror documentation](https://codemirror.net/examples/autocompletion/):

![Screenshot 2024-06-03 at 18 04 05](https://github.com/jsonnext/codemirror-json-schema/assets/32737387/452f91db-1eac-426c-a1a6-f36494deb6f4)

**Comment by kmarkussen** [comment]
I would also appreciate this feature

**Comment by acao** [comment]
@vharny terribly sorry that this shortcut was dropped in 2.x accidentally

**Comment by acao** [comment]
@vharny you can enable this with configuration in codemirror 6 (the docs you linked to are for 5), we are just a language mode library!

**Comment by acao** [comment]
if you want this feature in codemirror 6, please use the @codemirror/commands library

https://codemirror.net/docs/ref/#commands
