### ISSUE TITLE
Module not found - Webpack can't resolve not fully specified paths

### ISSUE THREAD

**Issue by Aleafan** [jsonnext/codemirror-json-schema#93]
Hello, thanks a lot for your work!

I use Webpack v.5.89.0 for bundling and get following errors:
![image](https://github.com/acao/codemirror-json-schema/assets/76619902/674d41ba-5309-40bd-8f96-ce9d417b90ac)

It was already mentioned in https://github.com/acao/codemirror-json-schema/issues/57 and seems connected to webpack's resolve.fullySpecified rule defaulting to true - https://webpack.js.org/configuration/module/#resolvefullyspecified. Setting fullySpecified to false solves the problem.

But it looks like more correct solution would be to put .js extensions in those imports as it seems to be recommended practice.

**Comment by acao** [comment]
@Aleafan can you try again with the latest release?

**Comment by acao** [comment]
in fact, i am 99% sure the latest release will solve this, but let us know if we need to re-open the ticket

**Comment by Aleafan** [comment]
Hello, I checked with latest release v.0.7.8 and it still doesn't work without fixing webpack config.

Webpack rule is if you set "type": "module" in package.json then you SHOULD provide the file extension when importing a module in .mjs files or any other .js files.

I guess we need to reopen the ticket.)
