### ISSUE TITLE
Issue with curly braces in default

### ISSUE THREAD

**Issue by alekseyg** [jsonnext/codemirror-json-schema#96]
It appears that the default gets mangled when it contains curly braces. For example, I have this schema:
```JSON
{
  "type":"object",
  "properties":{
    "message":{
      "type":"object",
      "properties":{
        "heading":{
          "type":"string",
          "default":"✨ A message from %{whom}: ✨"
        },
        "organizer":{
          "type":"string",
          "default":"the organizer"
        },
        "content":{
          "type":"string",
          "default":"[Message to your donors]"
        }
      }
    }
  }
}
```
But when I type out the key for `message.heading` and the default gets populated, it looks like this:
```JSON
{
  "message": {
    "heading": "✨ A message from %{whom\: ✨}"
  }
}
```
A backslash is inserted where the closing curly bracket should be and the curly bracket moves to the end of the string. It's also invalid JSON. I have more values like this with and without emoji, and the result is the same.

**Comment by alekseyg** [comment]
After playing around with it a little more it appears that it only mangles the first one. Here's an example with multiple curly braces.

Default in schema:
```JSON
"You made a %{amount} donation on %{date} to %{beneficiary}%{via}."
```

Mangled value inserted:
```JSON
"You made a %{amount\ donation on %{date} to %{beneficiary}%{via}.}"
```

**Comment by imolorhe** [comment]
I can reproduce the issue. It looks like an [issue](https://discuss.codemirror.net/t/inserting-literal-via-snippets/8136/4) upstream in codemirror.

**Comment by acao** [comment]
@alekseyg can you let us know if upgrading your  `@codemirror/autocomplete` version and upgrading to the latest release of our library resolve this issue?

**Comment by alekseyg** [comment]
@acao Yes! That fixed it. Thank you!
