### ISSUE TITLE
Error verification

### ISSUE THREAD

**Issue by mlj18293180341** [jsonnext/codemirror-json-schema#97]
Is there a validation method for organizing data submission, similar to form validation

**Comment by imolorhe** [comment]
Could you clarify your question? Maybe illustrate with an example?

**Comment by mlj18293180341** [comment]
> Could you clarify your question? Maybe illustrate with an example?

Sorry, there was an issue with my previous problem description. What I meant was to call the method of the component to prevent event submission. I can verify the error now, but I cannot prevent the submission of data. I saw the doValidate method in the source code, but it was not exported

**Comment by imolorhe** [comment]
I still think this needs some clarification. codemirror-json-schema provides codemirror extensions to be used as part of codemirror based editors. It doesn't handle anything related to data or event submission. It sounds like you need to raise this issue with [codemirror](https://discuss.codemirror.net/) itself? Perhaps there's more relevant help there as this doesn't sound related to codemirror-json-schema

**Comment by acao** [comment]
perhaps you are looking for something to validate data with your json schema for other purposes? there are many libraries, including ajv and json schema library which we use to validate runtime data. we just provide a codemirror mode that implements such tools.

for example, there is a react hook json forms library, and many similar libraries for other frameworks!
